title = 'Thingsboard instance definition'

[source]
host = 'riverflow.io'
port = 8080
user = 'MyThingsBoardUsername'
password = 'MyThingsBoardPassword'
devices = ['RL000282', 'RL000283']
variables = ["h", "t", "v"]